'use client'
import Logo from '@/components/Logo'
import './globals.css'
import { Saira_Stencil_One as Stencil, Saira } from 'next/font/google'
import Input from '@/components/Input'
import { ShoppingBag } from 'lucide-react'
import { QueryClient, QueryClientProvider } from 'react-query'
import { FilterProvider } from '@/contexts/FilterContext'

const stencil = Stencil({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-stencil'
})

const saira = Saira({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-saira'
})

export const metadata = {
  title: 'Caputeeno | RS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  const client = new QueryClient()

  return (
    <html lang="en">
      <body className={`${saira.variable} ${stencil.variable} font-saira bg-gray-100`}>
        <header className='w-full bg-white py-3 px-9 flex items-center justify-between'>
          <Logo />

          <div className='flex items-center gap-8 text-gray-400'>
            <Input />

            <ShoppingBag size={20} />
          </div>
        </header>

        <QueryClientProvider client={client}>
          <FilterProvider>
            <main className='py-9 px-9 w-full h-full flex flex-col gap-6'>
              {children}
            </main>
          </FilterProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
